### ISSUE TITLE
Github Task List

### ISSUE THREAD

**Issue by cyberay01** [cse112-sp20/CalamariCrew#30]
As a developer I want to have my task list in the extension so that I don't have to go all the way to GitHub to see it (L, Total = 16 hrs)

- [x] (Name: Get Tasks in Current Sprint, Description: Use github API to pull all tasks from your selected repo, filter your tasks that are allocated to this sprint, display them. Estimate: 8 hrs)
- [x] (Name: Update Tasks, Description: Repull data on response to tasks being changed so that tasks menu always shows the current tasks needed to be completed. Estimate: 5)
- [x] (Name: Update velocity, Description: Calculate current velocity based off of how many tasks are left. Estimate: 3)

**Comment by KenLHua** [comment]
Need Unit Test
